KitwareMedical/ITKTubeTK

Applications/SegmentConnectedComponents/SegmentConnectedComponents.cxx, Applications/SegmentConnectedComponents/SegmentConnectedComponents.xml
This pull request applies the minSize cutoff in physical space as opposed to image space.
=> BugFix: Modified SegmentConnectedComponents to apply minSize cutoff in physical space

Base/Filtering/itktubeTortuositySpatialObjectFilter.hxx, Base/Numerics/Testing/tubeTubeMathTest.cxx, Base/Numerics/tubeTubeMath.h, Base/Numerics/tubeTubeMath.hxx
=> Tortuosity computations

Base/Numerics/Testing/itktubeRidgeBasisFeatureVectorGeneratorTest.cxx, Base/Numerics/itktubeBasisFeatureVectorGenerator.hxx
Test was seg faulting due to access outside of matrix range.
=> BUG: BasisFeature computation was ignoring NumberOfLDA arg

Applications/ConvertTubesToTubeTree/ConvertTubesToTubeTree.xml, Applications/ConvertTubesToTubeTree/README.md, Applications/ConvertTubesToTubeTree/itktubeMinimumSpanningTreeVesselConnectivityFilter.h, Applications/ConvertTubesToTubeTree/itktubeMinimumSpanningTreeVesselConnectivityFilter.hxx, Base/Numerics/tubeTubeMath.h, Base/Numerics/tubeTubeMath.hxx, SlicerModules/SpatialObjectsModule/MRML/vtkMRMLSpatialObjectsNode.cxx
* Fixed vessel view tree display bugs
* Added way to explore root tubes by decreasing order of "out degree and tube length" instead of "out degree and number of points"
* Added a function to tubeTubeMath to compute tube length
=> Fixed vessel view tree display bugs and added way to order by tube length

Base/Filtering/Testing/itktubeTortuositySpatialObjectFilterTest.cxx, Base/Filtering/itktubeTortuositySpatialObjectFilter.h, Base/Filtering/itktubeTortuositySpatialObjectFilter.hxx
Remove unused variables
Change int to size_t
=> WARN: fix warnings introduced by NewMetricsAndBugFixes

Applications/ClipTubes/ClipTubes.cxx, Applications/ClipTubes/ClipTubes.xml, Applications/TubeMath/TubeMath.cxx
Many style errors in ClipTubes.  Also bug in use of spacing.   Also, probably still has logic issues regarding physical/index space.
=> ClipTubes and TubeMath

Applications/VesselTrainMask/VesselTrainMask.cxx
Reverts KitwareMedical/TubeTK#547
=> Revert "COMP: Fixed the error related to ImageReaderType"

Applications/TubeMinimalPathExtraction/CMakeLists.txt, Applications/TubeMinimalPathExtraction/README.md, Applications/TubeMinimalPathExtraction/TubeMinimalPathExtraction.cxx, Applications/TubeMinimalPathExtraction/TubeMinimalPathExtraction.xml, CMake/Superbuild/CMakeLists.txt, CMake/Superbuild/ExternalProjectsConfig.cmake, CMake/Superbuild/External_MinimalPathExtraction.cmake
This PR enables the MinimalPathExtraction module to be built externally in TubeTK Superbuild against the latest version of ITK.
=> Minimal path extraction external build

CMake/KWStyle/KWStyle.Overwrite.txt, SlicerModules/SpatialObjectsModule/MRML/vtkMRMLSpatialObjectsNode.cxx, SlicerModules/SpatialObjectsModule/MRML/vtkMRMLSpatialObjectsNode.h
1. m_SelectedTubeIds: Set of int containing the tubeids of the selected
tubes.
2. m_Default Color Map: Color map of the spatial object as read from the
input TRE file.
=> ENH: Added two new members in vtkMRMLSpatialObjectsNode

Applications/TubeTKModules.cmake, Base/Registration/CMakeLists.txt
This commit conditionally build applications and base filters depending
on VTK.
Co-authored-by: Lucas Gandel <lucas.gandel@kitware.com>
=> COMP: Fix building without VTK

Base/Numerics/Testing/itktubeNJetImageFunctionTest.cxx, Base/Numerics/itktubeBasisFeatureVectorGenerator.hxx, Base/Numerics/itktubeNJetImageFunction.hxx, Base/Numerics/tubeMatrixMath.hxx
Error in logic for computation of gaussian derivative functions.
=> BUG: Logic for derivative and hessian computation at scale

Applications/SegmentTubeUsingMinimalPath/SegmentTubeUsingMinimalPath.cxx, Applications/SegmentTubeUsingMinimalPath/SegmentTubeUsingMinimalPath.xml
Added an option to extract minimum path given one 3d point and a centerline.
Exposed the radius extraction parameters to the user - StartRadius , MaxRadius  and StepRadius
=> ENH: Extract minimum path given a 3d point and centerline.

Base/Numerics/Testing/itktubeNJetBasisFeatureVectorGeneratorTest.cxx, Base/Numerics/itktubeBasisFeatureVectorGenerator.hxx, Base/Numerics/itktubeFeatureVectorGenerator.hxx, Base/Numerics/tubeMatrixMath.hxx
Missing vnl_matrix_inverse include.
Incorrect assignment statement created non-symmetrix matrix for meanCovariance.
Extra couts removed from base code.
=> BUG: Non-symmetric matrix created.  COMP: Removed couts.  BUG: include

CMakeLists.txt
ENH: Changed 2D support to default to ON.  This will also fix several failing tests.
STYLE: Fixed spacing issues in CMakeLists.txt file (needed spaces between parens and their content.
=> ENH: TubeTK should support 2D images by default - used in tests

CMake/Superbuild/CMakeLists.txt
Alphabetize arg list.
Removed comment from arg list.
=> BUG: Removed comment from arg list

Base/Numerics/itktubeSingleValuedCostFunctionImageSource.hxx, CMake/Superbuild/ExternalProjectsConfig.cmake
Improvement of [#688](https://github.com/KitwareMedical/TubeTK/pull/688#issuecomment-215765459) by bumping ITK version to the new version used in Slicer.
=> Lucas gandel fix itk array.set data call bump itk version

Base/Segmentation/itktubePDFSegmenterBase.hxx, Base/Segmentation/itktubePDFSegmenterParzen.hxx, Base/Segmentation/itktubeRidgeSeedFilter.hxx
The switch to RecusiveGaussian was incorrectly implemented for Histograms - needed to apply in each dimension to generate a smooth PDF.
=> Ridge seed generator

Base/Numerics/tubeMatrixMath.hxx
Reverted to code that had been deleted in commit https://github.com/KitwareMedical/TubeTK/pull/635/files
Specifically added back code for 2D and 3D eigensolvers.   Tests indicate that these methods provide improved results compared to the generic vnl symmetric eigensolver.
=> ENH: Provide Eigensolver specific to 2D and 3D problem systems

Applications/ShrinkImage/CMakeLists.txt, Applications/ShrinkImage/README.md, Applications/ShrinkImage/ShrinkImage.cxx, Base/Filtering/itktubeShrinkWithBlendingImageFilter.h, Base/Filtering/itktubeShrinkWithBlendingImageFilter.hxx, ITKModules/TubeTKITK/include/tubeShrinkWithBlendingImage.h, ITKModules/TubeTKITK/include/tubeShrinkWithBlendingImage.hxx, ITKModules/TubeTKITK/include/tubeWrappingMacros.h, ITKModules/TubeTKITK/wrapping/tubeShrinkWithBlendingImage.wrap
Creation of a shadow class that mirrors the class in Base/Filtering
to allow the ITK wrap process to work.
Creation of an Python script in the application directory which
is the reimplementation of the C++ executable, using the wrapped
class.
=> ENH: Wrapping of ShrinkImage in Python

Base/Filtering/itktubeShrinkWithBlendingImageFilter.h, Base/Filtering/itktubeShrinkWithBlendingImageFilter.hxx, ITKModules/TubeTKITK/include/tubeShrinkWithBlendingImage.h, ITKModules/TubeTKITK/include/tubeShrinkWithBlendingImage.hxx
SetShrinkFactor(unsigned int, unsigned int) was declared but not defined.
=> BUG: Missing definition of SetShrinkFactor(unsigned int, unsigned int)

Applications/TreeMath/CMakeLists.txt, Applications/TreeMath/TreeMath.cxx, Base/Filtering/CMakeLists.txt, Base/Filtering/tubeTreeFilters.h, Base/Filtering/tubeTreeFilters.hxx
ENH: Created a tube namespace class for TreeMath command type application.
=> ENH: Reorganized Tree Math functions into a class in base/filtering.

Examples/SegmentVesselsUsingNeuralNetworks/scripts/ConvertData.py, Examples/SegmentVesselsUsingNeuralNetworks/scripts/PreProcessing.py, Examples/SegmentVesselsUsingNeuralNetworks/scripts/TrainNet.py, Examples/SegmentVesselsUsingNeuralNetworks/scripts/create_imageset.sh, Examples/SegmentVesselsUsingNeuralNetworks/scripts/params.json, Examples/SegmentVesselsUsingNeuralNetworks/scripts/saveSlabs.py
* remove hard-coded paths for `caffe_root` (caffe source directory) and `hardDrive_root` (path to directory where the portable hard disk for storing data/results is mounted) and getting them from a file called `params.json`
* address portability issues with path joins.
* refactor code
=> CNN-Vessel-seg: Address portability issues and remove hard-coded stuff

CMake/KWStyle/KWStyle.kws.xml, CMake/KWStyle/KWStyle.kws.xml.in, CMake/Superbuild/ExternalProjectsConfig.cmake
Update to most recent KWStyle.
Enable check for one space after ( and before )
Enable check for one space after comma
Enable check for no spaces after if, while, for or until.
=> ENH: Bump KWStyle and setup new style checks.

Applications/SegmentTubes/SegmentTubes.cxx
Tests to confirm the import of a previous vessel mask (Test 3) and the import of a previous set of extracted vessels (Test 4) were expected to result in no new vessels being extracted - which should be reported as a failure.    However, application's logic for verifying that new vessels were extracted was missing after update to wrapped classes.   This commit adds that logic back.
=> BUG: When no tubes are extracted, SegmentTubes should EXIT_FAILURE

CMake/Superbuild/CMakeLists.txt, CMake/Superbuild/ExternalProjectsConfig.cmake, CMake/Superbuild/External_RandomForest.cmake, CMake/TubeTKBlockSetCMakeOSXVariables.cmake, CMakeLists.txt
Created superbuild scripts and cmakelist option for build Random Forest
Updated MacOS Root and SDK code to include support for El Capitan
=> ENH: Update Mac OSX Name and Build Random_Forest

CMake/Superbuild/ExternalProjectsConfig.cmake
Updating ITK as the second part of patch [1].
[1] https://github.com/KitwareMedical/TubeTK/commit/1caeae5a7f0294eb07082c457ca8679ca8b6dcd2
=> BUG: ITKModule binary include directory only included if ENABLE_SHARED

Examples/SegmentVesselsUsingNeuralNetworks/scripts/utils.py
This contains some common utils used by other scripts.
Forgot to add this file in the last PR #910 .
=> Adding utils.py to CNN vessel seg example

Examples/SegmentVesselsUsingNeuralNetworks/scripts/PrepareTrainingData.py, Examples/SegmentVesselsUsingNeuralNetworks/scripts/TestNet.py, Examples/SegmentVesselsUsingNeuralNetworks/scripts/TrainNet.py, Examples/SegmentVesselsUsingNeuralNetworks/scripts/utils.py
This is a series of refactorings, mainly of `Examples/SegmentVesselsUsingNeuralNetworks/scripts/PrepareTrainingData.py`. Documentation has also been added to many of the functions in it.
These changes affect the printed output *very* slightly, but should not otherwise affect the input or output of the script.
=> Clean up and document PrepareTrainingData.py in SegmentVesselsUsingNeuralNetworks

Applications/SegmentVesselsCNNSeeds/SegmentVesselsCNNSeeds.py
Create the output directory as necessary
=> Change output directory behavior for SegmentVesselsCNNSeeds

Applications/SegmentVesselsCNNSeeds/SegmentVesselsCNNSeeds.py
This fixes errors when creating the preprocessed images
=> Create directory, if necessary, before preprocessing files as well

Applications/Convert4DImageTo3DImages/CMakeLists.txt, Applications/Convert4DImageTo3DImages/Convert4DImageTo3DImages.cxx, Applications/Convert4DImageTo3DImages/Convert4DImageTo3DImages.xml, Applications/Convert4DImageTo3DImages/README.md, Applications/TubeTKModules.cmake
Separates a 4D image file (e.g., 4D CT) into a sequence of 3D image files.
=> ENH: New CLI for extracting 3D images from a 4D image

CMakeLists.txt, TubeTKLib/Common/CMakeLists.txt, TubeTKLib/CompareTools/CMakeLists.txt, TubeTKLib/Filtering/CMakeLists.txt, TubeTKLib/IO/CMakeLists.txt, TubeTKLib/Numerics/CMakeLists.txt, TubeTKLib/ObjectDocuments/CMakeLists.txt, TubeTKLib/Segmentation/CMakeLists.txt, TubeTKLib/USTK/CMakeLists.txt, apps/CMakeLists.txt
Add cmake conditionals for using non-standard packages
=> ENH: Make VTK, SEM, Apps, and Python use optional

CMake/FindNumPy.cmake
Numpy is required for converting Tubes to NumPy Arrays.
=> ENH: Added FindNumPy.cmake to confirm numpy installation

CMakeLists.txt
TubeTK_BUILD_APPLICATION -> TubeTK_BUILD_APPLICATIONS
=> BUG: Typo in cmake variable blocked building apps

dashboards/dashboardDate.sh
Force master to be rebuilt - not a branch.
=> ENH: Push nightly date file changes directly to master

apps/ComputeBinaryImageSimilarityMetrics/ComputeBinaryImageSimilarityMetrics.cxx
Revert output format to match test expectations
=> BUG: ComputeBinaryImageSimilarityMetricsTest

setup.py, test/CMakeLists.txt, test/azure-pipelines.yml
Including files in new ITK Cookie Cutter module
=> ENH: Updated to use ITK5.0 on dashboards/azure

TubeTKLib/Segmentation/itktubeSegmentTubes.hxx
=> BUG: fixing duplicate transform from physical to index coordinates

TubeTKLib/Segmentation/CMakeLists.txt, TubeTKLib/Segmentation/itktubeSegmentTubeUsingMinimalPathFilter.h, TubeTKLib/Segmentation/itktubeSegmentTubeUsingMinimalPathFilter.hxx, apps/SegmentTubeUsingMinimalPath/SegmentTubeUsingMinimalPath.cxx, include/itkTubeTK_fake_library_src.h, include/tubeSegmentTubeUsingMinimalPath.h, include/tubeSegmentTubeUsingMinimalPath.hxx, wrapping/tubeSegmentTubeUsingMinimalPath.wrap
Use consistent naming of SegmentTube(not-plural)UsingMinimalPath
=> ENH: MinimalPathExtraction extracts a single tube

TubeTKLib/Filtering/tubeImageMathFilters.h, examples/ConvertTubesToImage.ipynb, examples/TubeNumPyArrayAndPropertyHistograms.ipynb
Now duplicates the input image before processing.
Updated examples too.
=> BUG: ImageMath was modifying input image.

apps/ConvertTubesToImage/ConvertTubesToImage.xml
=> BUG: Adding label to parameter in CLI xml file for ConvertTubesToImage

Readme.md
Provide an initial description of the update build process, now that TubeTK is available as an ITK remote module
=> Update Readme.md for ITK remote module

CMakeLists.txt
Reverts KitwareMedical/ITKTubeTK#1159
=> Revert "ENH: Remove install target that wasn't used"
