SlicerModules/SpatialObjectsModule/Widgets/qSlicerSpatialObjectsModuleWidget.cxx
SlicerModules/SpatialObjectsModule/Widgets/qSlicerSpatialObjectsWidget.cxx
SlicerModules/SpatialObjectsModule/Widgets/qSlicerSpatialObjectsWidget.h

Before, the function setSpatialObjectDisplay() associated
the first display node of the passed node.
Now we can choose which display node it should be associated with.

Add arg to specify which display node qSlicerSpatialObjectWidget drives

---

Base/Registration/itkBSplineImageToImageRegistrationMethod.txx
Base/Registration/itkImageToImageRegistrationHelper.txx

This was forgotten in commit 1e0d898, because it was
tested on TubeTK standalone and not TubeTK with Slicer

Replace ITKv3 compatibility functions by ITKv4 functions

---

Applications/ComputeRegionSignatures/ComputeRegionSignatures.cxx
Base/Numerics/Testing/tubeTubeMathTest.cxx
Base/Registration/itkAnisotropicSimilarity3DTransform.h
Base/Registration/itkAnisotropicSimilarity3DTransform.txx
Base/Registration/itkImageToImageRegistrationHelper.txx
Base/Segmentation/Testing/itktubeRadiusExtractorTest.cxx
CMake/TubeTKBlockSetCMakeOSXVariables.cmake

Fixed formatting per KWStyle specification.
Updated handling of CMake OSX vars based on BlockSet macro from Slicer.
Updated TubeMathTest.

ENH: Update BlockSetOSCXVars from Slicer, TubeMathTest, Style

---

SlicerModules/SpatialObjectsModule/Widgets/qSlicerSpatialObjectsWidget.cxx

- https://github.com/KitwareMedical/VesselView/issues/30
Crash when selecting a spatialobjectnode, on an assert error in a ctkRangeWidget.
Needed to set SingleStep before Range
- https://github.com/KitwareMedical/VesselView/issues/93
ColorByScalarComboBox has wrong behavior when switching between 2 nodes
Needed to set CurrentArray of ColorByScalarComboBox in updateWidgetFromMRML

BUG: Fix 3 issues in SpatialObjects Module

---

Base/IO/itktubeTubeXIO.hxx
Base/Numerics/Testing/tubeTubeMathTest.cxx
Base/Numerics/tubeTubeMath.hxx

- Fix crash when selecting Gaussian Distance smoothing method which isn't yet implemented
- Correct cout to cerr in tubeTubeMathTest.
- Remove duplicate points when converting TubeX to TubeTK format -> avoid warnings

Gaussian distance smoothing crash

---

CMakeLists.txt

to make sure that tubetkConfigure.h is seen when built by vesselview/slicer

Fix: Adding TubeTK_BINARY_DIR to TubeTK_INCLUDE_DIRS

---

Base/CMakeLists.txt
Base/Filtering/CMakeLists.txt
Base/Filtering/Testing/itktubeExtractTubePointsSpatialObjectFilterTest.cxx
Base/Filtering/itktubeExtractTubePointsSpatialObjectFilter.h
Base/Filtering/itktubeExtractTubePointsSpatialObjectFilter.hxx
Base/Numerics/CMakeLists.txt
Base/Numerics/tubeTubeMath.h
Base/Numerics/tubeTubeMath.hxx
Base/ObjectDocuments/CMakeLists.txt
Base/ParameterSerializer/CMakeLists.txt
Base/Python/CMakeLists.txt

Output data structure was being de-allocated because of mixing of raw and smart pointers.
Now preserving output data structure as a member variable.

BUG: avoid de-allocation of container in ExtractTubePointsSpatialObjectFilter

---

Base/Common/ImageCompareCommand.cxx

Namespace itksys_ios is no longer used in ITK 4.9.
Replaced by namespace std when using ostringstream

BUG: Replace namespace itksys_ios by std

---

Base/Common/CMakeLists.txt

This commit adds ITKMetaIO as a dependency for the CompareCommand
modules from Base/Common.
This fixes the following error [1] thrown by the TextCompareCommand
and JsonCompareCommand modules.
[1] : undefined reference to `MetaCommand::MetaCommand()'

BUG: Fix MetaCommand linking error

---

Applications/ClipTubes/ClipTubes.cxx
Applications/ClipTubes/ClipTubes.xml
Applications/ClipTubes/README.md

This commit enables us to be more precise when we determine if a
tube belongs to the bounding box, by taking into account the tube
orientation in physical space. 
Compare-Test are expected to fail.

ENH: Improve detection for box belonging

---

CMake/CTestCustom.cmake.in

Suppress Dashboard warning:
TubeTK-Release/ITK/Modules/Core/Common/include/itkImageRegionConstIteratorWithIndex.hxx:37:5: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]

COMP: Suppress an ITK warning about overflow.

---

CMake/Superbuild/External_SlicerExecutionModel.cmake
CMake/Superbuild/External_VTK.cmake

SlicerExecutionModel (like VTK) does not have a robust Find_JsonCpp cmake file.  JsonCpp libraries must be explicitly passed.

BUG: Must pass JSonCpp_LIBRARIES to SlicerExecutionModel 

---

CMake/CTestCustom.cmake.in

Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "KIT_TEST_SRCS" will no longer be dereferenced when
the policy is set to NEW.  Since the policy is not set the OLD behavior
will be used.
Call Stack (most recent call first):
SlicerModules/SpatialObjectsModule/Testing/Cxx/CMakeLists.txt:29 (SlicerMacroConfigureGenericCxxModuleTests)

COMP: Suppress Slicer cmake macro warning regarding unquoted if args

---

SlicerModules/SpatialObjectsModule/Logic/vtkSlicerSpatialObjectsLogic.cxx

itksys_stl::string has been replaced by std::string in KWSys in ITK [1]. ITK has been updated in Slicer and TubeTK was not compiling when enabling TubeTK_BUILD_WITHIN_SLICER.
[1] https://github.com/InsightSoftwareConsortium/ITK/commit/daf08c37f4e0d9269b0b84911487994b0a81e002

COMP: Remove itksys_stl::string calls

---

Applications/SegmentTubeUsingMinimalPath/CMakeLists.txt
CMake/Superbuild/ExternalProjectsConfig.cmake
CMake/Superbuild/External_MinimalPathExtraction.cmake

This commit fixes Ubuntu and OSX build when a version prior
to ITK 4.9 is used. For those builds to success, a specific
branch of the MinimalPathExtraction repository is cloned.
It also fixes Windows build issues using ITK 4.9 by bumping
the MinimalPathExtraction version.

BUG: Adapt MinimalPathExtraction version to ITK version

---

Applications/SegmentTubeUsingMinimalPath/CMakeLists.txt
CMake/Superbuild/ExternalProjectsConfig.cmake
CMake/Superbuild/External_MinimalPathExtraction.cmake

* Choose source repo and sha for ITKMinimalPathExtraction based on ITK revision
* ITK revision must be > 4.8.1 for building as an external extension in ITK
* Change checkout of extension to a specific sha, instead of a branch, even when ITK <= 4.8.1

BUG: Update ITK version test to > 4.8.1 and fixed checkout of extension

---

Applications/ComputeTrainingMask/ComputeTrainingMask.cxx
Applications/TubeTKModules.cmake

ComputeTrainMask.cxx was including VTK headers, but it did not use any VTK functions/classes.   The headers have been removed.  Building ComputeTrainMask is no longer conditional on VTK.

Remove unused vtk includes

---

Base/Numerics/CMakeLists.txt

This commit adresses the issue thrown when TubeTK_USE_GPU_ARRAYFIRE
is set to ON. Arrayfire libraries were linked to the TubeTKNumerics
target using target_link_libraries without any signature.
Further in the code, TubeTKCommon libraries are linked to the same
target using the PUBLIC signature.
According to https://cmake.org/cmake/help/v3.0/policy/CMP0023.html,
the NEW behavior for CMake policy doesn't allow plain and keyword
signatures.
Adding a PUBLIC target_link_libraries signature for Arrayfire libraries
fixed it.
The error can be found at : https://open.cdash.org/viewBuildError.php?buildid=4228536

BUG: Fix TubeTKNumerics target_link_libraries using Arrayfire

---

Applications/ConvertTubesToTubeTree/itktubeMinimumSpanningTreeVesselConnectivityFilter.h
Applications/ConvertTubesToTubeTree/itktubeMinimumSpanningTreeVesselConnectivityFilter.hxx

Fixed an issue, the tubes which were not connected to the root tree were not getting added to the output.
A root tube with no children, was considered a orphan and was not added to the output if removeOrphanTubes parameter was set.

Convert tube to tube tree

---

Applications/SegmentTubeUsingMinimalPath/SegmentTubeUsingMinimalPath.cxx

Added an else condition to prevent calling isNear function after the
clipping is finished.

ENH: Replaced tube::Message with std::cout to prevent cdash error.

---

Base/Numerics/tubeMatrixMath.hxx

Remove warning comparison between signed and unsigned integer expressions.

COMP: Remove warnings

---

Applications/SegmentTubeUsingMinimalPath/SegmentTubeUsingMinimalPath.cxx

The global variable INT32_MAX was added in PR #569 but it creates an error on Ubuntu 12.04 according to the dashboard. Including <stdint.h> should be enough to fix the issue but because CircleCI doesn't test TubeTk build on Ubuntu 12.04, we'll have to merge and wait for the continuous results.

COMP: Fix undefined INT32_MAX global variable

---

ITKModules/ITKTubeTK/test/CMakeLists.txt

This commit adresses the following issue :
```
Unknown CMake command "itk_add_test"
(itk_module_kwstyle_test)
(itk_module_impl)
ITKModules/ITKTubeTK/CMakeLists.txt:8 (include)
```
It is adding an empty test directory to satisfy `ITKModuleExternal.cmake`
requirements when the ITK version that is used doesn't contain the
patch InsightSoftwareConsortium/ITK@2c51c92.

COMP: Fix ITKTubeTK module testing

---

Applications/ConvertTubesToDensityImage/itktubeTubeSpatialObjectToDensityImage.hxx
Base/Filtering/itktubePadImageFilter.hxx
Base/Filtering/itktubeSmoothingRecursiveGaussianImageFilter.hxx
Base/Filtering/itktubeStructureTensorRecursiveGaussianImageFilter.hxx
Base/Numerics/itktubeBlurImageFunction.hxx
Base/Numerics/itktubeVotingResampleImageFunction.hxx
Base/Registration/itkAffineImageToImageRegistrationMethod.txx
Base/Registration/itkImageToImageRegistrationHelper.txx
Base/Registration/itkInitialImageToImageRegistrationMethod.txx
Base/Registration/itktubeAnisotropicDiffusiveRegistrationFilter.hxx
Base/Registration/itktubeAnisotropicDiffusiveRegistrationFunction.hxx
Base/Registration/itktubeAnisotropicDiffusiveSparseRegistrationFilter.hxx
Base/Registration/itktubeDiffusiveRegistrationFilter.hxx
Base/Segmentation/itktubeCVTImageFilter.hxx
Base/Segmentation/itktubeRidgeExtractor.hxx
CMake/Superbuild/CMakeLists.txt
CMake/Superbuild/ExternalProjectsConfig.cmake
CMake/TubeTKMacroAddModules.cmake
CMakeLists.txt
ITKModules/CMakeLists.txt
SlicerModules/SpatialObjectsModule/Testing/Cxx/CMakeLists.txt
SlicerModules/TortuosityModule/Logic/vtkSlicerTortuosityLogic.cxx

In addition of fixing warnings, this set of changes will:
* allow to build against old version of Slicer
* update `vtkMRMLSpatialObjectsNode` to adapt to backward incompatible change related to `Reset` method

Easier integration of tubetk

---

CMake/TubeTKMacroAddModules.cmake

This commit fixes a regression introduced in af33b91 (COMP: Pass
TubeTK_BUILD_ALL_MODULES and TubeTK_BUILD_* to inner build).
Configure error:
```
CMake Error at CMake/TubeTKMacroAddModules.cmake:85 (mark_as_superbuild):
Unknown CMake command "mark_as_superbuild".
Call Stack (most recent call first):
Applications/TubeTKModules.cmake:119 (TubeTKMacroAddModules)
Applications/CMakeLists.txt:28 (include)
```
Reported-by: Stephen Aylward <Stephen.Aylward@kitware.com>

COMP: Fix configure error due to unknown "mark_as_superbuild" command

---

CMake/CircleCI/CircleCI_slicer_Docker/Dockerfile

This commit updates the Slicer GIT_TAG in the Dockerfile.
The new image has been built using the build.sh script and
pushed to DockerHub using the push.sh script.

ENH: Update Slicer's version on Docker

---

ITKModules/TubeTKITK/include/tubeCropImage.h

This commit adresses the issue thrown when building TubeITK inside
the ITK build tree. See [1].
It adds the CropImage class from tubeCropImage.h in the TubeTKITK group.
[1]: https://open.cdash.org/testDetails.php?test=428387946&build=4272919

BUG: Fix TubeTKITKInDoxygenGroup test

---

Base/Numerics/tubeMatrixMath.hxx

Was incorrectly assigning using the get function, rather than the set function of vnl matrix columns.

BUG: Was not re-ordering eigenvectors correctly.

---

Base/Filtering/itktubeRidgeFFTFilter.hxx
Base/Numerics/tubeMatrixMath.hxx

Matrix computations were creating non-symmetric matrices due to precision limits.  FixSymmetric after these computations to avoid eigensolver inconsistencies.

ENH: When solving eigen analysis, force symmetry due to precision limits

---

Applications/TubeTKModules.cmake
Base/IO/CMakeLists.txt
Base/IO/Testing/CMakeLists.txt
Base/IO/Testing/tubeBaseIOHeaderTest.cxx
Base/IO/Testing/tubeBaseIOPrintTest.cxx
Base/IO/Testing/tubeBaseIOTests.cxx
Base/Segmentation/CMakeLists.txt
Base/Segmentation/Testing/CMakeLists.txt
Base/Segmentation/Testing/tubeBaseSegmentationHeaderTest.cxx
Base/Segmentation/Testing/tubeBaseSegmentationPrintTest.cxx
Base/Segmentation/Testing/tubeBaseSegmentationTests.cxx
CMake/tubetkConfigure.h.in

This commit fixes a regression introduced in 55a11b4 (ENH: Initial
implementation of LIBSVM-based PDFSegmenter)

Fix TubeTK build with TubeTK_USE_LIBSVM option set to OFF

---

Applications/ComputeSegmentTubesParameters/ComputeSegmentTubesParameters.cxx

Keeping false positive low while increasing vessel length (reduced
stopping criteria)

ENH: Experimenting with parameter generation.

---

Base/Filtering/itktubeTortuositySpatialObjectFilter.hxx
SlicerModules/SpatialObjectsModule/MRML/vtkMRMLSpatialObjectsNode.h
SlicerModules/TortuosityModule/Widgets/qSlicerTortuosityModuleWidget.cxx

vtkMRMLSpatialObjectNode: ‘virtual void
vtkMRMLNode::Reset(vtkMRMLNode*)’ was hidden by ‘virtual void
vtkMRMLSpatialObjectsNode::Reset()’
itktubeTortuositySpatialObjectFilter: comparison of unsigned expression
< 0 is always false
qSlicerTortuosityModuleWidget: unused variable q

COMP: Fixed compiler warnings.

---

SlicerModules/TortuosityModule/Logic/vtkSlicerTortuosityLogic.cxx
SlicerModules/TortuosityModule/Logic/vtkSlicerTortuosityLogic.h

Volume of each tube is calculated as the sum of volumes of cylinders made by
consecutive points where radius is (r(t) + r(t+1))/2 and height is the
distance between two points.

ENH: Added volume metrics in the basic metric group of tortuosity module

---

Base/Segmentation/itktubeRidgeSeedFilter.hxx

This commit fixes #665. After reading the discriminant information,
the PDF Segmenter was overwritten in the Update() function of
itktubeRidgeSeedFilter.hxx.

BUG: PDF Segmenter overwritten by RidgeSeedFilter.Update()

---

CMake/Superbuild/ExternalProjectsConfig.cmake

This includes
Slicer/SlicerExecutionModel@8d607ff93a3be76274d9cedfb9f1148a6cdb6968
which makes the binary size of CLI's smaller and makes them load faster. This
commit has already been integrated into Slicer.

ENH: Bump SEM for smaller sized CLI's that load faster.

---

CMake/CircleCI/CircleCI_slicer_Docker/Dockerfile

ENH: Bump CircleCI Docker image Slicer version.

---

CMake/CheckPythonLibrary.cmake
CMakeLists.txt

If one tries to build TubeTK with the option TubeTK_USE_NUMPY
and if numpy is not available on the system, TubeTK will not
compile correctly. To avoid receiving an error message at compilation
time, a test to verify that numpy is available at configuration
time.

ENH: Check if numpy is available on the system

---

CMake/Superbuild/ExternalProjectsConfig.cmake

This includes
InsightSoftwareConsortium/ITK@5aa604c9942612957dd0d6f2bf8f2fbca928885b
which should address dashboard build errors like:
TubeTK-Debug/TubeTK-build/ITKModules/MinimalPathExtraction/test/MinimalPathTest.h:211:
undefined reference to `itk::NumericTraits::Zero'

COMP: Update ITK to address itk::NumericTraits::Zero build errors.

---

CMake/Superbuild/ExternalProjectsConfig.cmake

This is a follow-up to
KitwareMedical/TubeTK@2b3fe664eee25653dc0c391feae95ff87079d768
The github.com/Slicer/ITK.git repository does not have a copy of the ITK
master branch and the commit is missing.
This causes the build failure:
Error
CMake Error at Stamp/ITK/ITK-download-Release.cmake:16 (message):
Command failed: 1
'C:/Program Files (x86)/CMake/bin/cmake.exe' '-P' '/.../TubeTK-Release/tmp/ITK/ITK-gitclone.cmake'
See also
/.../TubeTK-Release/Stamp/ITK/ITK-download-*.log

BUG: Fix the ITK clone URL.

---

Base/Filtering/itktubeRidgeFFTFilter.hxx
Base/Numerics/itktubeNJetImageFunction.hxx
Base/Numerics/tubeMatrixMath.h
Base/Numerics/tubeMatrixMath.hxx
Base/Segmentation/itktubeRidgeExtractor.h
Base/Segmentation/itktubeRidgeExtractor.hxx

Before computing ridgeness, roudness, curvature and levelness, the
ComputeRidgeness function now checks for the tangent and normals
direction and reorder them if needed.

BUG: ComputeRidgeness checks for tangent direction

---

CMakeLists.txt

When calling message(FATAL "..."), the configuration process is not
interrupted and one can still generate the project. The key word
that needs to be used in CMake to stop the configuration is
'FATAL_ERROR'.

BUG: FATAL instead of FATAL_ERROR in CMakeLists.txt

---

ITKModules/TubeTKITK/wrapping/tubeComputeBinaryImageSimilarityMetrics.wrap

tubeComputeBinaryImageSimilarityMetrics should only be wrapped for
integers types, not for float and double.

BUG: tubeComputeBinaryImageSimilarityMetrics works only for integers

---

Applications/ComputeBinaryImageSimilarityMetrics/ComputeBinaryImageSimilarityMetrics.cxx
Base/CLI/tubeCLIHelperFunctions.h

If an application supports only integer pixel types, it is
now possible to use ParseArgsAndCallDoIt() and the templated
function DoIt() to handle all integer types
(such as 'int', 'short',...) without supporting float types.

ENH: PARSE_ARGS_INT_ONLY added to ParseArgsAndCallDoIt()

---

CMakeLists.txt

When building TubeTK as a Slicer extension withing Slicer (e.g. as
part of VesselView), CACHE variables that are passed to TubeTK
should not be unset as they are not reset by SlicerConfig.cmake.
Indeed, in this case, SlicerConfig.cmake does not contain values
for these CACHE variables. The SlicerConfig.cmake file used in
this case is not the one contained in the build directory of Slicer,
but the one contained in the subdirectory containing the extensions.

ENH: CACHE variables should not always be removed

---

Base/Segmentation/itktubeSegmentTubesUsingMinimalPathFilter.h
Base/Segmentation/itktubeSegmentTubesUsingMinimalPathFilter.hxx

Include files from MinimalPathExtraction need to be found
by CastXML when wrapping TubeTKITK. Therefore
MinimalPathExtraction needs to be added as a dependency of
TubeTKITK. This will allow to generate the .inc file
that contains all the path to the include files used by
TubeTKITK.

BUG: MinimalPathExtraction is a dependency for TubeTKITK

---

Applications/SegmentTubeUsingMinimalPath/SegmentTubeUsingMinimalPath.cxx
Base/Segmentation/itktubeSegmentTubesUsingMinimalPathFilter.h
Base/Segmentation/itktubeSegmentTubesUsingMinimalPathFilter.hxx
ITKModules/TubeTKITK/include/tubeSegmentTubesUsingMinimalPath.h

ENH: Removed extra options from the application.
Since spatial object is an optional input to this application, the itk
filter should not be drived from SpatialObjectToSpatialObjectFilter.

ENH: Changed the base class for SegmentTubesUsingMinimumPath filter.

---

CMakeLists.txt

By default, no Python virtual environment is created to run tests. The tests
are run in the user's environment, which helps verifying that their environment
is set up correctly.

ENH: Creation of a Python virtual environment is optional

---

Base/Numerics/itktubeComputeImageStatistics.h
Base/Numerics/itktubeComputeImageStatistics.hxx

When compiling in Debug, itkSetMacro() calls itkDebugMacro() which
print the value of the variable that is set. If ones uses itkSetMacro
with a type that cannot directly be printed, compilation will
work in Release, but not in Debug.

BUG: itkSetMacro() handles only types that can be printed

---

ITKModules/TubeTKITK/test/CMakeLists.txt
ITKModules/TubeTKITK/test/ComputeTrainingMaskPythonTest.py

ComputeTrainingMaskPythonTest should not be running if Python wrapping
is disabled. Paths to include itk and TubeTKITK within the test
have been updated to rely on environment variables.

BUG: ComputeTrainingMaskPythonTest ran with Python wrapping OFF

---

CMake/Midas3FunctionAddTest.cmake
CMake/TubeTKTestEnvironmentVariables.cmake
CMakeLists.txt
Examples/TubeNumPyArray/Testing/CMakeLists.txt
ITKModules/TubeTKITK/test/CMakeLists.txt
ITKModules/TubeTKITK/test/ComputeTrainingMaskPythonTest.py
Testing/CMakeLists.txt

When running python scripts that use TubeTK wrapped in Python,
one needs to set their environment so that the libraries are loaded.
This can be done two ways:
-Copy WrapITK.pth from TubeTK-build/Generators/Python/ or setting
ITK_BUILD_DIR and TubeTK_BUILD_DIR environment variables. Because tests
are develop to verify that TubeTK works correctly, they replicate the
expected behavior of a user. Python tests set these two environment
variables before running the tests. This is done by calling the
new TubeTK function Midas3FunctionWithEnvAddTest.
Additionally, a test has been added to verify that the environment
variables are set on the system and match the expected value
of these variables in this project. This test can be deactivated
by setting TubeTK_TEST_ENVIRONMENT to OFF (e.g. on a …

ENH: Set environment variables for Python tests

---

Base/Segmentation/itktubeSegmentTubesUsingMinimalPathFilter.hxx

The code converts a vertex (an index) to a physical point then converts back to an index manually.  This seems redundant and causes the output to be incorrect for images with non-standard scan order.

BUG: Minimal path segmentation doesn't handle output correctly

---

CMake/CircleCI/CircleCI_slicer_Docker.cmake
circle.yml

CircleCI build are constrained by a 4Gb memory limit. See
https://circleci.com/docs/oom/
The compiler checks for the number of cores available on the machine.
The output of "lscpu" shows 32 cores on the entire machine. However,
builds are running in a single container that shares cores with other
currently running containers.
The output of "top" shows that the compiler try to use all cores
and can dedicate up to 1Gb of memory for each job :
PID  USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
17714 root      20   0  622m 578m  11m R   12  0.2   0:42.30 cc1plus
17797 root      20   0  692m 647m  11m R   12  0.3   0:39.37 cc1plus
[...]
17570 root      20   0  840m 791m  11m R    4  0.3   0:46.91 cc1plus
17723 root      20   0  729m 682m  10m R    4  0.3   0:38.86 cc1plus …

COMP: CircleCI compiler crash because container runs out of memory

---

CMake/TubeTKMacroAddModules.cmake
CMakeLists.txt

Fixed multiple style errors (Line length, indentation, space after paren).
Updated TubeTK_USE_PYTHON to use the new CMAKE_DEPENDENT_OPTION.
Removed USE_EXAMPLES_AS_TESTS dependency on Python.

BUG: Using examples as tests does not require python.

---

ITKModules/TubeTKITK/test/CMakeLists.txt
ITKModules/TubeTKITK/test/ComputeTrainingMaskPythonTest.py

To test TubeTKITK wrapped in Python, we setup the environment
variable TubeTK_BUILD_DIR. This variable was set to the wrong
path: It was set using the CMake variable PROJECT_BINARY_DIR
which was not pointing to TubeTK inner build directory
but rather to the TubeTK wrapping directory.

BUG: Wrong path TubeTK_BUILD_DIR

---

SlicerModules/SpatialObjectsModule/MRML/vtkMRMLSpatialObjectsNode.cxx

Points are being read as double but vtkPoints stores floats by default.  This loss of precision can cause very close points to become coincident.

BUG: Fixed loss of precision when reading and storing points

---

CMakeLists.txt

Also, the usage of the set command for this option was incorrect. The [syntax](https://cmake.org/cmake/help/v3.0/command/set.html) of cmake's set command is
```
set(<variable> <value>
[[CACHE <type> <docstring> [FORCE]] | PARENT_SCOPE])
```

BUG: Make TubeTK_USE_EXAMPLES_AS_TESTS as an option

---

ITKModules/TubeTKITK/test/CMakeLists.txt
ITKModules/TubeTKITK/test/PythonComputeTrainingMaskTest.py

The paths of the directory containing WrapITK.pth files required to import
ITK and TubeTK in Python on Windows contain the configuration that is chosen
at build time.

BUG: Testing Python module on Windows requires knowing configuration

---

Base/Registration/itktubeAnisotropicDiffusiveSparseRegistrationFilter.hxx
CMakeLists.txt

These are two minor changes that improves compatibility with latest version of 3D Slicer.
One change is just to make TubeTK compatible with a changed API in VTK7.
The other change is to facilitate building of TubeTK as an extension by Slicer factory machines. It only fixes build errors, there are still issues in building the extension package.

Improve compatibility with 3D Slicer

---

Base/IO/CMakeLists.txt

TubeTKIO directory no longer has non-templated code, so no TubeTKIO library is created.
Using "modern cmake" we define TubeTKIO as an INTERFACE.
It may be necessary to delete cmake caches (e.g., reconfigure and rebuild from scratch) after this commit.

BUG: TubeTKIO library is now simply an interface - no library created

---

Applications/ResampleImage/ResampleImage.cxx
Base/Filtering/itktubeResampleImageFilter.hxx
ITKModules/TubeTKITK/include/tubeComputeSegmentTubesParameters.hxx
ITKModules/TubeTKITK/include/tubeConvertSpatialGraphToImage.hxx
ITKModules/TubeTKITK/include/tubeCropImage.hxx
ITKModules/TubeTKITK/include/tubeCropTubes.hxx
ITKModules/TubeTKITK/include/tubeEnhanceContrastUsingPrior.hxx
ITKModules/TubeTKITK/include/tubeResampleImage.h
ITKModules/TubeTKITK/include/tubeResampleImage.hxx
ITKModules/TubeTKITK/include/tubeSegmentTubesUsingMinimalPath.hxx

ResampleImageFilter must call GraftOutput() on itk filter used in its Update function.
Wrapped filters should have complete PrintSelf functions.

BUG: ResampleImages and PrintSelf for wrapped functions

---

CMake/TubeTKTestEnvironmentVariables.cmake

Comparing the expected value of ITK_BUILD_DIR (respectively TubeTK_BUILD_DIR)
with the corresponding environment variable might not pass when comparing
the strings of the paths if the paths are not set in the same format
or if a path is relative and the other one absolute even if these
paths correspond to the same folder. On Windows, an additional problem
could come from the path in the environment variables being set
with back-slashes (Windows format) whereas CMake paths use forward-slashes
(UNIX format).

BUG: Compares absolute paths for ITK_BUILD_DIR and TubeTK_BUILD_DIR

---

Base/Segmentation/Testing/CMakeLists.txt

On some platforms a few (211) pixels at the boundaries between classes are classified differently.  Increased tolerance to 300 to account for machine/seed/randomization/optimization variances.

BUG: Increase tolerance for PDFSegmenterSVM test - class boundaries

---

CMakeLists.txt

Find JsonCpp using custom FindJsonCpp in TubeTK/CMake - which searches for proper directories given JsonCpp_DIR.   Otherwise, VTK's FindJsonCpp is used, and TubeTK's JsonCpp is not found.

ENH: SlicerExecutionModel now required JsonCpp

---

CMakeLists.txt
SlicerModules/SpatialObjectsModule/MRML/vtkMRMLSpatialObjectsTubeDisplayNode.cxx

* Update TubeTKLauncher.bat generator to include JSconCpp, if TubeTK's JsonCpp isn't used (it is static)
* Fixed bugs in TubeTKLauncher.bat generator cmake commands (e.g., incorrect syntax and missing conditional on USE_BOOST)
* Removed unused includes that referenced non-existent files from old version of VTK/Slicer

Update for Slicer4.6 compatibility

---

Applications/CropImage/CropImage.cxx

Use 0-padded numbering for filename sequences generated when an image is split into multiple regions.
This 0-padding follows the format:
<basename>-ZZZZYYYYXXXX.mha
Where ZZZZ is the Z-th split in the Z dimension, specified using 0 padding to 4 characters.   So, if you split a 100 slice file into 20 files along the z-dimension, the file names will be:
<basename>-000000000000.mha
<basename>-000100000000.mha
<basename>-000200000000.mha
....
<basename>-001900000000.mha

ENH: Improve filenames generated when splitting using CropImage

---

Utilities/GitSetup/hooks/commit-msg

commit-msg script may have been copied from a different project and simplified.
The function "msg_rest" is missing which leads to a message being printed
in the terminal when a git commit is done. This commit adds an empty function
that could be improved if necessary.

BUG: Missing msg_rest function in git commit hook

---

Base/IO/itktubeRidgeSeedFilterIO.hxx

Closing bracket corresponding to the opening bracket defined only
if TubeTK_USE_LIBSVM is defined is only necessary when TubeTK_USE_LIBSVM
is defined.

BUG: Missing TubeTK_USE_LIBSVM preprocessor conditional

---

ITKModules/CMakeLists.txt

If an ITK module is built with ENABLE_SHARED, a file is created in the module
binary include directory. Otherwise, the module binary include directory
does not exist and should not be added to the list of include directories
of the module.

WIP: ITKModule binary include directory only included if ENABLE_SHARED

---

CMake/Superbuild/ExternalProjectsConfig.cmake

This commit should have been part of commit d8e6470206d9a574b1069ee6569c235c3d89da00 [1]
but ITK patch 68d0b9021c003d809929615adcdc171cbaec4f2e [2] had not been merged in ITK yet.
[1] https://github.com/KitwareMedical/TubeTK/commit/d8e6470206d9a574b1069ee6569c235c3d89da00
[2] https://github.com/InsightSoftwareConsortium/ITK/commit/68d0b9021c003d809929615adcdc171cbaec4f2e

ENH: Update ITK to install module target files in subdirectory

---

Applications/ComputeImageStatistics/ComputeImageStatistics.cxx
Base/Filtering/itktubeConvertImagesToCSVFilter.h
Base/Filtering/itktubeConvertShrunkenSeedImageToListFilter.h
Base/Filtering/itktubeExtractTubePointsSpatialObjectFilter.h
Base/Numerics/itktubeVectorImageToListGenerator.h
Base/ObjectDocuments/itktubeObjectDocumentToObjectSource.h
Base/Segmentation/itktubeRidgeSeedFilter.h
Base/USTK/itkUltrasoundProbeGeometryCalculator.h
Base/USTK/itktubeMarkDuplicateFramesInvalidImageFilter.h
CMake/CTestCustom.cmake.in
CMake/Superbuild/ExternalProjectsConfig.cmake
ITKModules/TubeTKITK/include/tubeConvertImagesToCSV.h
ITKModules/TubeTKITK/include/tubeConvertShrunkenSeedImageToList.h

Was exposing un-supported SetInput methods, and now they are masked
by private void implementations instead.
Fixed unused typedefs.
Masked numpy deprecated and LIBSVM deprecated warnings from dashboard
Bumped ITK version

COMP: Improved handling of SetInput hidding, fix warnings, bump ITK

---

Applications/SegmentTubeUsingMinimalPath/CMakeLists.txt

When an ITK module is used, it might have been built as a remote module.
Include directories of remote modules are given in a module-specific cmake file
that is included when ITK is included in a project, but the paths
for that module are not included when ITK include paths are included.
The paths of a remote module must be specifically included by applications
that use them.

BUG: Add paths associated with MinimalPathExtraction module

---

CMake/CTestCustom.cmake.in

Addressed the warnings:
Slicer-Release/ITKv4/Modules/Core/Common/include/itkAtomicIntDetail.h:137:12: warning: 'OSAtomicAdd64Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from  instead [-Wdeprecated-declarations]
Slicer-Release/ITKv4/Modules/Core/Common/include/itkAtomicIntDetail.h:259:5: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from  instead [-Wdeprecated-declarations]

COMP: Supress warnings from MacOS10.12: OSAtomic/OSMemory deprecated API

---

Applications/SegmentTubeUsingMinimalPath/CMakeLists.txt

If MinimalPathExtraction is built using ITK in Slicer, then
the path to the MinimalPathExtractionExport.h file needs to be
explicitely set when it is built at the same time an application
that uses it is built.

COMP: Set path to MinimalPathExtraction-build/include

---

Examples/SegmentVesselsUsingNeuralNetworks/scripts/ConvertData.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/ExtractVessels.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/PreProcessing.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/PrepareTrainingData.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/ProcessNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TestNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TrainNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/UnShrink.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/create_imageset.sh
Examples/SegmentVesselsUsingNeuralNetworks/scripts/params.json
Examples/SegmentVesselsUsingNeuralNetworks/scripts/reconstructSlabs.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/saveSlabs.py

This PR consolidates the data preprocessing, CNN training and testing into just three scripts for which involved running several scripts earlier:
* **PrepareTrainingData.py** - This generates the Z-MIP slabs for all datasets, splits control and tumor datasets equally into training and validation sets, generates +ve and -ve patches for training the CNN, and creates the caffe LMDB files 
* **TrainNet.py** - This defines the CNN architecture, trains the CNN in an epoch-wise (earlier we were doing in terms of iteration), saves the CNN filters after each epoch, plots the learning curve, and random samples of patches falling in each element of the confusion matrix for debugging.
* **TestNet.py** - This uses the trained CNN to segment vessels on all datasets in the testing set. Specifically, it …

US CNN Vessel seg - Generalize old code and consolidate preprocessing, training, and testing

---

Examples/ShrinkImage/GenerateInputMipPointImageTest/CMakeLists.txt
Examples/ShrinkImage/GenerateInputMipPointImageTest/GenerateInputMipPointImageTest.cxx

This is the code that generates the images for the test of `ShrinkImage`'s `--inputMipPointImageTest` option. If this should have more documentation or be moved elsewhere, let me know.

ShrinkImage test generation code

---

Examples/SegmentVesselsUsingNeuralNetworks/scripts/PrepareTrainingData.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TestNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TrainNet.py

Some small bug fixes for the SegmentVesselsUsingNeuralNetworks example.
- Fix calls to `ShrinkImage` via `subprocess.call` by separating flags from their arguments.
- Change the `matplotlib` backend to avoid requiring TK
- Move the call to `caffe.set_mode_gpu()` up in `TrainNet.py` as Caffe currently requires (though undocumented) GPU mode to be set before creating a solver, else it crashes.

SegmentVesselsUsingNeuralNetworks small bug fixes

---

Examples/SegmentVesselsUsingNeuralNetworks/scripts/PrepareTrainingData.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TestNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TrainNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/params.json

The current directory setup makes it difficult to reuse input data across multiple configurations / experiments. It also requires placing the data in Caffe's source directory.
This PR puts all generated data together, leaving the input directory untouched, and lets the input directory be placed anywhere. Note that, because `PROJECT_REL_PATH` has been removed, the special case of giving the input and output directories the same name has no shortcut -- but it is no longer the only option.

Separate input and output directories in SegmentVesselsUsingNeuralNetworks

---

Examples/SegmentVesselsUsingNeuralNetworks/scripts/PrepareTrainingData.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TestNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/TrainNet.py
Examples/SegmentVesselsUsingNeuralNetworks/scripts/params.json
Examples/SegmentVesselsUsingNeuralNetworks/scripts/utils.py

Convert the `SegmentVesselsUsingNeuralNetworks` example to use Keras instead of Caffe, due to the former's greater flexibility and better documentation.
At the moment this removes the ability to specify different learning rate decay functions other than Keras' default, and filter visualization is only done at the end of training, not every epoch. The frequency at which training performance is recorded is also reduced to every epoch from every iteration.
On-disk, two things have been changed:
- First, extracted patches are stored in a subdirectory named after the slice image they are from instead of all in one folder. This seems to increase the speed at which the database is built when a large number of patches are extracted.
- The database used is now SQLite instead of LMDB

Convert SegmentVesselsUsingNeuralNetworks to Keras

---

Applications/SegmentTubes/SegmentTubes.cxx
Applications/SegmentTubes/SegmentTubes.xml

This PR teaches `SegmentTubes` the option `--seedListPhysicalNoScale`, which accepts a file whose lines are the physical coordinates of seed points, using a separately set scale.
It also documents the format expected by the existing `--seedList` option, and fixes a small typo in the description of the `--seedP` option.

Add an option to SegmentTubes to take a seed point file with points in physical coordinates

---

Base/Filtering/itktubeTubeSpatialObjectToImageFilter.hxx
ITKModules/TubeTKITK/include/tubeConvertTubesToImage.hxx

The `ConvertTubesToImage` program seems to fail to properly handle template images with non-zero offset, nor is there any mention made of the direction information in the code. While the pixel data in the output image appears correct, its origin and direction are fixed at zero and identity, respectively.
I'm running into problems trying to fix this The Right Way™️, however. Simply passing the origin and direction through breaks things.  Instead chaining `TubeSpatialObject::GetIndexToWorldTransform().TransformPoint` and `Image::TransformPhysicalPointToContinuousIndex` for the coordinate transformation doesn't help. Interestingly, stopping with passing the origin and direction through restores functionality with the changed coordinate transformation in place.
The TRE files are probably …

WIP: ConvertTubesToImage issue

---

PythonModules/tubetk/vseg/cnn/deploy.py

There's way too much of it, and this is a quick and easy fix for it.
This will also silence `SegmentTubes` when using the `TestNet` script.

Ignore SegmentTubes' output in SegmentVesselsCNNSeeds

---

CMake/CTestCustom.cmake.in

Warning suppressed =
warning: #warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK" [-Wcpp]
Coverage suppressed =
Wrapping

ENH: Disable warnings and remove Wrapping from coverage computation

---

CMake/KWStyle/Headers/BatHeader.txt
CMake/Superbuild/ExternalProjectsConfig.cmake
CMake/TubeTKBlockSetCMakeOSXVariables.cmake
CMakeLists.txt

No longer test for using Qt on MacOS compiled prior to 10.8.
Use an externaldata directory for downloaded data, if an environment
var specifies one.

ENH: Remove reference to Qt.  Support env vars for externaldata.

---

Base/Segmentation/itktubeRidgeExtractor.hxx
Base/Segmentation/itktubeTubeExtractor.hxx
ITKModules/TubeTKITK/include/tubeSegmentTubes.h

ExtractBounds is an index, so should be directly addressed in
Get/Set macros.
Also, reduced threshold on Roundness - making it less sensitive.

BUG: Python wrapping of SegmentTubes accessing Index as object

---

Applications/SegmentBinaryImageSkeleton3D/CMakeLists.txt
Applications/SegmentBinaryImageSkeleton3D/README.md
Applications/SegmentBinaryImageSkeleton3D/SegmentBinaryImageSkeleton3D.cxx
Applications/SegmentBinaryImageSkeleton3D/SegmentBinaryImageSkeleton3D.xml
Applications/TubeTKModules.cmake
Base/Filtering/CMakeLists.txt
Base/Filtering/itktubeBinaryThinningImageFilter3D.h
Base/Filtering/itktubeBinaryThinningImageFilter3D.hxx
Base/Segmentation/CMakeLists.txt
Base/Segmentation/itktubeSegmentBinaryImageSkeleton3D.h
Base/Segmentation/itktubeSegmentBinaryImageSkeleton3D.hxx
ITKModules/TubeTKITK/include/tubeSegmentBinaryImageSkeleton3D.h
ITKModules/TubeTKITK/include/tubeSegmentBinaryImageSkeleton3D.hxx
ITKModules/TubeTKITK/wrapping/tubeSegmentBinaryImageSkeleton3D.wrap

This adapts the itkBinaryThinningImageFilter3D from http://hdl.handle.net/1926/1292 for inclusion in TubeTK. It adds
1. itktubeBinaryThinningImageFilter3D to Base/Filtering
2. itktubeSegmentBinaryImageSkeleton3D to Base/Segmentation
3. tubeSegmentBinaryImageSkeleton3D to ITKModules/TubeTKITK for wrapping
4. SegmentBinaryImageSkeleton3D to Applications
One thing to note is that, because of how wrapping is done, building of the Application is turned off when TubeTK_SUPPORT_2D_IMAGES is on because the underlying filter only supports 3D images. 
I have tested the CLI in Slicer and it seems to work, I have not yet tested the python wrapping.

Add BinaryThinningImageFilter3D from IJ article

---

ITKModules/TubeTKITK/include/tubeSegmentTubes.h
ITKModules/TubeTKITK/include/tubeSegmentTubes.hxx
ITKModules/TubeTKITK/tubetk-depends.cmake

Adds method `SetParameterFile` to `itk.SegmentTubes`

ENH: Support setting parameter files in Python-wrapped SegmentTubes

---

apps/CLI/tubeCLIHelperFunctions.h
apps/SegmentBinaryImageSkeleton3D/SegmentBinaryImageSkeleton3D.cxx

Select apps only work with 3D images.   The CLI helper function (Do_It) is typically templated by image dimension and supports 2D and 3D images.   The commit allows an app to #define a variation to enable only having a 3D template argument for image dimension during compilation.

ENH: Add option to CLI Helper Function to only compile app for 3D

---

dashboards/AzureLinuxGCC/azure-pipelines.yml
dashboards/AzureMacOSGCC/azure-pipelines.yml
dashboards/AzureWinVS/azure-pipelines.yml

This also requires building SlicerExecutionModel prior to building
TubeTK and requires access to ITK Source and Binary dirs.

ENH: Turn on building apps on Azure

---

TubeTKLib/Registration/Testing/itktubeTubeParametricExponentialResolutionWeightFunctionTest.cxx
TubeTKLib/Registration/Testing/itktubeTubeParametricExponentialWithBoundsResolutionWeightFunctionTest.cxx
TubeTKLib/Registration/itktubeTubeToTubeTransformFilter.hxx

Assigning doubles to float - changed vars to double
Unused vars

COMP: Fix warnings regarding type conversion and unused vars

---

TubeTKLib/Numerics/itktubeVotingResampleImageFunction.h

When merging the last commit (UpdateToITKv5), a manual merge
was required to resolve a conflict, and a bug was introduced.
This addresses that bug in itktubeVotingResampleImageFunction.h

BUG: Fix duplicate function definition from bad merge

---

test/azure-pipelines.yml

Testing in Azure now allows C++ to test against one git tag of ITK while python testing is against 
a different tag.    Using so that TubeTK can track C++ master and Python latest wheel.

ENH: Take advantage of support for separate python and C++ git tags

---

TubeTKLib/Filtering/itktubeResampleTubesFilter.h
TubeTKLib/Filtering/itktubeResampleTubesFilter.hxx
TubeTKLib/Filtering/itktubeStructureTensorRecursiveGaussianImageFilter.h
TubeTKLib/Filtering/itktubeStructureTensorRecursiveGaussianImageFilter.hxx
TubeTKLib/Registration/itkImageToImageRegistrationHelper.txx
apps/ResampleTubes/ResampleTubes.cxx
apps/TubeMath/TubeMath.cxx

Ubuntu18 compiler revealed bugs in const-ness between ITK and ITKTubeTK.
Also removed throw() keywords in member function declarations.

BUG: Fixed const-ness of transformlists and SpatialObjects

---

apps/CLI/tubeCLIHelperFunctions.h

Remove support for char, double, and unsigned int.

ENH: Limit types supported by apps to those that are common

---

include/tubeSegmentConnectedComponentsUsingParzenPDFs.h

Missing override in
include/tubeSegmentConnectedComponentsUsingParzenPDFs.h

COMP: Override needed.

---

TubeTKLib/Registration/Testing/CMakeLists.txt
TubeTKLib/Registration/Testing/itktubeImageToTubeRigidRegistrationTest.cxx
TubeTKLib/Registration/itktubeImageToTubeRigidMetric.h
TubeTKLib/Registration/itktubeImageToTubeRigidMetric.hxx

In parallel with updates to ITK (pull request #1198 which updated the TubeSpatialObject's IsInside function), this update fixes the baseline for the indicated test.

BUG: Updated baseline for itktubeImageToTubeRigidRegistration

---

TubeTKLib/Filtering/itktubeConvertShrunkenSeedImageToListFilter.hxx

Add test and exception if the shrunken image and its parameter images
that track the scale and x,y,z coordinates in the shrunken image, don't
match in size.

BUG: Check for same size images in ConvertShrunkenSeedImageToList

---

TubeTKLib/Filtering/tubeImageMathFilters.h
TubeTKLib/Filtering/tubeImageMathFilters.hxx
apps/ImageMath/ImageMath.cxx

Results are not as expected occasionally on select platforms.  Results
are inconsistent (sometimes perfect, other times with small deviations).
Using radius as int instead of float, to see if rounding/float errors
are to blame.

BUG: Occasionally ImageMath Test 9 fails - morphological erode

---

TubeTKLib/Registration/itktubeImageToTubeRigidMetric.h
TubeTKLib/Registration/itktubeImageToTubeRigidMetric.hxx

When declaring functions in .h files and defining them (e.g., in .hxx
files), C++11 has deprecated the use of "throw(exception)" in the
function declaration statements. The message is
```
warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
::Initialize(void) throw ( ExceptionObject )
^~~~~
```

COMP: C++11 has deprecated the "throw" function declaration decorator

---

TubeTKLib/Numerics/tubeMatrixMath.hxx
TubeTKLib/Segmentation/Testing/itktubeRidgeExtractorTest2.cxx
TubeTKLib/Segmentation/itktubeRidgeExtractor.hxx

If RidgeExtractor returned null (e.g., ridge too short) then the test
would segment fault because it would attempt to use that null pointer.

BUG: RidgeExtractorTest2 using potentially null pointer.

---

TubeTKLib/Filtering/tubeImageMathFilters.hxx

Following design pattern in other systems to store morphological output
in a temp variable prior to assigning to input var.   Shouldn't matter,
but perhaps optimizations are causing trouble and this avoids them.

BUG: Address randomly failing morphological filter with temp var

---

apps/RegisterImageToTubesUsingRigidTransform/Testing/CMakeLists.txt

Convert file-based dependencies to test-name-based dependencies to
facilitate parallel testing

BUG: Dependencies of RegisterImageToTubesUsingRigidTransform tests

---

TubeTKLib/Segmentation/Testing/itktubeRidgeExtractorTest2.cxx

itktubeRidgeExtractorTest2 test intermittently fails, this adds more debugging when it fails.

COMP: Add more debugging to test that intermittently fails

---

TubeTKLib/CompareTools/CompareImages.cxx

If the direction matrix had swapped direction in the input image,
then the SubMatrix option for ExtractImageFilter would fail.  This
commit changes it to use SetIdentity.   Output images seem valid.

BUG: CompareImages failed to generate baselines

---

Readme.md

ITKTubeTK now requires:
* ITK 5.1rc01 or later
* SEM hashtag ef094e7140d71b5e75675f63910d39acd1d7221d (balances bug fixes with unnecessary CMake version requirements)

Update Readme.md for ITK 5.1rc01 and SEM

---

CMakeLists.txt
TubeTKLib/Segmentation/itktubeRidgeExtractor.hxx
apps/ComputeTubeMeasures/CMakeLists.txt
apps/EnhanceTubesUsingDiscriminantAnalysis/CMakeLists.txt

Needed to update paths associated with TubeTK libraries and interfaces
to support use of arrayfire in Python-wrapped modules.

BUG: Re-enable arrayfire support.

---

TubeTKLib/Filtering/CMakeLists.txt

File is no longer part of ITKTubeTK, so we shouldn't list it.

BUG: CastSpatialObject filter moved to ITK, so remove install cmd
